# Generated by Django 4.0 on 2022-01-17 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time_stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='post_data',
            fields=[
                ('time_stamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IdeaShare.time_stamp')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('post_data_short', models.CharField(max_length=200)),
                ('thumb_cost', models.PositiveIntegerField(default=0)),
                ('long_approval', models.BooleanField(default=False)),
                ('post_data_long', models.TextField()),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IdeaShare.category_data')),
            ],
            bases=('IdeaShare.time_stamp',),
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('hint', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
                ('classes', models.CharField(blank=True, choices=[('P', 'Personal'), ('C', 'Company'), ('A', 'Admin'), ('H', 'High_Admin')], default='P', max_length=20)),
                ('Admin_Approval', models.BooleanField(default=False)),
                ('bulb', models.PositiveIntegerField(default=5)),
                ('coin', models.PositiveIntegerField(default=0)),
                ('follower', models.ManyToManyField(to='IdeaShare.user_data')),
                ('following', models.ManyToManyField(to='IdeaShare.user_data')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('time_stamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IdeaShare.time_stamp')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IdeaShare.user_data')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IdeaShare.post_data')),
            ],
            bases=('IdeaShare.time_stamp',),
        ),
        migrations.AddField(
            model_name='post_data',
            name='nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IdeaShare.user_data'),
        ),
    ]
