# Generated by Django 4.0 on 2022-01-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaShare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='follower',
            field=models.ManyToManyField(default='', related_name='following', to='IdeaShare.user_data'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='following',
            field=models.ManyToManyField(default='', related_name='follower', to='IdeaShare.user_data'),
        ),
    ]
